name: Gradr

on:
  push:
    branches:
    - main

jobs:
  autograde:
    name: Auto-Grade Code Changes
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout Your Code
      uses: actions/checkout@v4

    - name: Prepare Environment
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Acquire Audits
      uses: actions/checkout@v4
      with:
        repository: exam-01-practice/assignment-02-gradr-audits-js
        path: audits

    - name: Install Dependencies
      run: |
        npm install --location=global yarn
        cd audits
        yarn install

    - name: Review Challenge - 1
      run: |
        cd audits
        yarn audit-ch-1

    - name: Review Challenge - 2
      if: always()
      run: |
        cd audits
        yarn audit-ch-2

    - name: Review Challenge - 3
      if: always()
      run: |
        cd audits
        yarn audit-ch-3

    - name: Report Audits
      if: always()
      uses: oluwasetemi/jest-to-sheets-modified@v1
      with:
        challenge: 'ch-1;ch-2;ch-3'
        lang: javascript
        server: https://api.sheetson.com/v2/sheets
        sheetid: 1r4jloq3CKH4o6t5VgW-8fuRPkD3MEXP2FUEH6XXTSRs
        token: rLYJMutJkU2vF4N4V2En3LucORJhZVQ3LmIVbylHcrSowmnBLmsi-nIKPfI
